New test: accepted_range
fishtown-analytics/dbt-utils pull request #276
Opened 2020-09-07 11:11 UTC by joellabes

This is a:
- [ ] bug fix PR with no breaking changes (please change the base branch to `main`)
- [x] new functionality
- [ ] a breaking change

## Description & motivation
This adds an accepted_range test, allowing users to ensure things like that a percentage is between 0 and 100, or that all accounts were created in the past. Technically, if you made a test with a `min_value` of 'A' and `max_value` of '[', I guess you could also check that all names started with a capital letter, but you shouldn't.

I'm open to discussion on the min_value and max_value arguments. I'm tempted to call them greater_than and less_than because I feel like that might make more sense when you're not comparing a scalar number, but I think it's friendlier for the most common case right now.

## Checklist
- [ ] I have verified that these changes work locally on the following warehouses (Note: it's okay if you do not have access to all warehouses, this helps us understand what has been covered)
    - [ ] BigQuery
    - [ ] Postgres
    - [x] Redshift
    - [ ] Snowflake
- [x] I have updated the README.md (if applicable)
- [x] I have added tests & descriptions to my models (and macros if applicable)
- [ ] I have added an entry to the changelog

2020-09-08 13:45 UTC, clrcrl commented
This looks `:chefs_kiss:`. Lol.

I will test it out later this week :)

2020-09-08 15:19 UTC, clrcrl commented on README.md
> +            max_value: "getdate()"
I think this needs to be indented
```suggestion
              max_value: "getdate()"
```
Same for below snippets

2020-09-08 15:19 UTC, clrcrl commented on README.md
> +          - dbt_utils.accepted_range
missing a `:`
```suggestion
          - dbt_utils.accepted_range:
```
(below too)

2020-09-08 21:36 UTC, joellabes commented
@clrcrl README mistakes are fixed, thanks for catching them! I can see the CI tests failed but can't log into CircleCI to see why - are they mine?

2020-09-14 17:42 UTC, clrcrl requested changes
We're missing a `columns:` entry, which is causing the tests to fail

2020-09-14 17:42 UTC, clrcrl commented on integration_tests/models/schema_tests/schema.yml
> +          where: "id <> -1"
```suggestion
  - name: data_test_accepted_range
    columns:
      - name: id
        tests:
          - dbt_utils.accepted_range:
              min_value: -1
              max_value: 11
              inclusive: true

          - dbt_utils.accepted_range:
              min_value: -2
              max_value: 11.1
              inclusive: false

          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
              where: "id <> -1"

```

2020-09-14 22:50 UTC, clrcrl commented
Kickin' off those tests now!

2020-09-15 12:51 UTC, clrcrl approved these changes

2020-09-15 12:52 UTC, merged

2020-11-17 23:04 UTC, yu-iskw commented
Thank you for the great new feeature. I look forward to using it.
BTW, @clrcrl do you have a timeline to release dbt-utils==0.7.0?

2020-11-18 19:36 UTC, clrcrl commented
We'll be doing utils 0.7.0 in line with dbt-core 0.19.0, which I think is coming up in mid-December.

In the meantime, you can either:
(a) install 0.7.0 by including this in your `packages.yml`:

```
packages:
- git: https://github.com/fishtown-analytics/dbt-utils.git
  revision: dev/0.7.0
```

(b) copying this macro into your own project (in the `macros` directory). Note, you won't need to prefix the test name with `dbt_utils` in that case.

FWIW, I'd go with (b), just in case we introduce a breaking change into this branch

2020-12-15 00:31 UTC, yu-iskw commented
Thank you for sharing the knowledge. I will try it out.

2021-05-06 04:48 UTC, yu-iskw commented
@clrcrl Please let me know when 0.7.0 is out, if you know. If there is any blocker and anything I can contribute to, please let me know as well. Thanks.